### ISSUE TITLE
Unable to see the plugin 

### ISSUE THREAD

**Issue by mario-hernandez** [arafatkn/tableplus-ulid-generator#1]
Hi! Thanks for your work!

However after installing and executing it I see the option in the submenu when doing secondary click on a cell but no response got from the plugin execution...

**Comment by arafatkn** [comment]
Thanks for opening the issue. I have fixed the bug.
Please pull the latest changes from **master** branch or download the latest (>= v0.1.1) version from [release](https://github.com/arafatkn/tableplus-ulid-generator/releases)
I have tested in several devices, hope it will work on your device also.

Thank you again.
